import { z } from "zod";

export const comprehensivePlanContentSchema = z.object({
  main_disability: z.string().min(1, "主たる障害を入力してください"),
  long_term_goal: z.string().min(1, "長期目標を入力してください"),
  short_term_goal: z.string().min(1, "短期目標を入力してください"),
  goal_period: z.string().min(1, "目標達成期間を入力してください"),
  b21_checks: z.record(z.string(), z.boolean()).optional(),
  b21_text: z.record(z.string(), z.string()).optional(),
  treatment_content: z.string().optional(),
  comorbidities: z.string().optional(),
  rest_risk: z.string().optional(),
  contraindications: z.string().optional(),
  body_functions: z.string().optional(),
  basic_movements: z.string().optional(),
  adl_scores: z.string().optional(),
  assistive_devices: z.string().optional(),
  monthly_status: z.string().optional(),
  nutrition: z.string().optional(),
  oral: z.string().optional(),
  social_services: z.string().optional(),
  discharge_goal: z.string().optional(),
  treatment_policy: z.string().optional(),
  rehab_content: z.string().optional(),
  history_status: z.string().optional(),
  participation_goal: z.string().optional(),
  activity_goal: z.string().optional(),
  concrete_approach: z.string().optional(),
  family_info: z.string().optional(),
  home_environment: z.string().optional(),
  swallowing_status: z.string().optional(),
  swallowing_plan: z.string().optional(),
  guidance_content: z.string().optional(),
  service_coordination: z.string().optional(),
  discharge_notes: z.string().optional(),
  other_plan_notes: z.string().optional(),
  evaluation_date: z.string().optional(),
  pt_content: z.string().optional(),
  pt_frequency: z.string().optional(),
  ot_content: z.string().optional(),
  ot_frequency: z.string().optional(),
  st_content: z.string().optional(),
  st_frequency: z.string().optional(),
  precautions: z.string().optional(),
  doctor_name: z.string().optional(),
  consent_obtained: z.boolean().default(false),
  consent_date: z.string().optional(),
});

export const rehabDocumentSchema = z.object({
  patient_id: z.string().uuid("患者を選択してください"),
  document_date: z.string().min(1, "計画書作成日を入力してください"),
  valid_from: z.string().optional(),
  valid_to: z.string().optional(),
  content: comprehensivePlanContentSchema,
});

export type RehabDocumentFormData = z.infer<typeof rehabDocumentSchema>;
