import { z } from "zod";

export const comprehensivePlanContentSchema = z.object({
  main_disability: z.string().optional().default(""),
  long_term_goal: z.string().optional().default(""),
  short_term_goal: z.string().optional().default(""),
  goal_period: z.string().optional().default(""),
  treatment_content: z.string().optional(),
  comorbidities: z.string().optional(),
  rest_risk: z.string().optional(),
  contraindications: z.string().optional(),
  body_function_checks: z.record(z.string(), z.boolean()).optional(),
  body_function_texts: z.record(z.string(), z.string()).optional(),
  basic_movement_scores: z.record(z.string(), z.string()).optional(),
  fim_scores: z.record(z.string(), z.number().min(1).max(7).nullable()).optional(),
  assistive_devices: z.string().optional(),
  monthly_status: z.string().optional(),
  nutrition: z.string().optional(),
  oral: z.string().optional(),
  social_services: z.string().optional(),
  discharge_goal: z.string().optional(),
  treatment_policy: z.string().optional(),
  rehab_content: z.string().optional(),
  history_status: z.string().optional(),
  participation_goal: z.string().optional(),
  activity_goal: z.string().optional(),
  concrete_approach: z.string().optional(),
  family_info: z.string().optional(),
  home_environment: z.string().optional(),
  swallowing_status: z.string().optional(),
  swallowing_plan: z.string().optional(),
  guidance_content: z.string().optional(),
  service_coordination: z.string().optional(),
  discharge_notes: z.string().optional(),
  other_plan_notes: z.string().optional(),
  evaluation_date: z.string().optional(),
  pt_content: z.string().optional(),
  pt_frequency: z.string().optional(),
  ot_content: z.string().optional(),
  ot_frequency: z.string().optional(),
  st_content: z.string().optional(),
  st_frequency: z.string().optional(),
  precautions: z.string().optional(),
  doctor_name: z.string().optional(),
  consent_obtained: z.boolean().default(false),
  consent_date: z.string().optional(),
  medical_institution: z.string().optional(),
  rehab_doctor: z.string().optional(),
  attending_doctor: z.string().optional(),
  creator_pt: z.string().optional(),
  creator_ot: z.string().optional(),
  creator_st: z.string().optional(),
  creator_nurse: z.string().optional(),
  creator_sw: z.string().optional(),
  creator_dietitian: z.string().optional(),
  explanation_person: z.string().optional(),
  exercise_device_disease: z.string().optional(),
  exercise_device_onset: z.string().optional(),
  exercise_device_findings: z.string().optional(),
  exercise_device_plan_detail: z.string().optional(),
});

export const rehabDocumentSchema = z.object({
  patient_id: z.string().uuid("患者を選択してください"),
  document_date: z.string().min(1, "計画書作成日を入力してください"),
  valid_from: z.string().optional(),
  valid_to: z.string().optional(),
  content: comprehensivePlanContentSchema,
});

export type RehabDocumentFormData = z.infer<typeof rehabDocumentSchema>;
